# Default values for vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


httpServicePort: &defaultServicePort 80
ingressHost: current-cluster-roost.io

services:
  voter: 
    image: zbio/voter:latest
    ingressEndpoint: "/voter/"
    serviceName: "voter"
    servicePort: *defaultServicePort
  ballot: 
    image: zbio/ballot:latest
    ingressEndpoint: "/ballot/"
    serviceName: "ballot"
    servicePort: *defaultServicePort
  electionCommission: 
    image: zbio/election-commission:latest
    ingressEndpoint: "/ec/"
    serviceName: "election-commission"
    servicePort: *defaultServicePort
  ecserver: 
    image: zbio/ecserver:latest
    ingressEndpoint: "/ecserver/"
    serviceName: "ecserver"
    servicePort: *defaultServicePort
