apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ballot
  name: {{ .Values.services.ballot.serviceName }}
spec: 
  type: NodePort
  selector: 
    app: ballot
  ports:
  - name: http
    port: {{ .Values.httpServicePort }}
    targetPort: 8080
    nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template:
    metadata:
      labels:
        app: ballot
    spec:
      containers:
      - name: ballot
        image: {{ .Values.services.ballot.image }}
        ports:
        - containerPort: 8080
