apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: voter
    type: "roost-example"
  name: {{ .Values.services.voter.serviceName }}
spec:
  type: NodePort
  selector: 
    app: voter
    type: roost-example
  ports:
  - name: http
    port: {{ .Values.httpServicePort}}
    targetPort: 80
    nodePort: 30030

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
      type: roost-example
  template:
    metadata:
      labels:
        app: voter
        type: roost-example
    spec:
      containers:
      - name: voter
        image: {{ .Values.services.voter.image }}
        stdin: true
        tty: true
        env:
        - name: REACT_APP_BALLOT_ENDPOINT
          value: {{ .Values.ingressHost }}{{ .Values.services.ballot.ingressEndpoint }}
        - name: REACT_APP_EC_SERVER_ENDPOINT
          value: {{ .Values.ingressHost }}{{ .Values.services.ecserver.ingressEndpoint }}
        ports:
        - containerPort: 80
